### ISSUE TITLE
getting VS Code to like JSX

### ISSUE THREAD

**Issue by mvolkmann** [kitajs/html#105]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

 "@kitajs/html": "^3.0.11",
 "@kitajs/ts-html-plugin": "^1.3.3",

### Description

VS Code doesn't like my use of JSX when I use this library. Here is a screenshot:

![Screenshot 2024-01-19 at 9 30 14 AM](https://github.com/kitajs/html/assets/79312/4cb2d011-19b7-4f80-879f-f4a3a16c9981)

Here is my `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "strict": true,
    "jsx": "react",
    "jsxFactory": "Html.createElement",
    "jsxFragmentFactory": "Html.Fragment",
    "plugins": [{"name": "@kitajs/ts-html-plugin"}]
  }
}
```

If I change `tsconfig.json` to the following, VS Code stops complaining about the JSX, but then I'm not using this library:

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "strict": true,
    "jsx": "react-jsx",
    "jsxImportSource": "hono/jsx"
  }
}
```

Here is the complete source file, `index.tsx`:

```ts
import {Hono} from 'hono';
import type {Context} from 'hono';
import type {FC} from 'hono/jsx';
import {Html} from '@kitajs/html';

const app = new Hono();

const BaseHtml: FC = ({children}) => (
  <html>
    <head>
      <title>Endpoint Returning Script</title>
      <script src="https://unpkg.com/htmx.org@1.9.9"></script>
      <script>console.log('Hello, World!');</script>
    </head>
    <body>{children}</body>
  </html>
);

app.get('/', (c: Context) => {
  return c.html(
    <BaseHtml>
      <h1>Endpoint Returning Script</h1>
    </BaseHtml>
  );
});

export default app;
```

### Steps to Reproduce

Open the source file above in VS Code.

### Expected Behavior

VS Code should not complain about the JSX in this source file.

**Comment by arthurfiorette** [comment]
Have you tried changing the TS LSP into the one installed into your workspace?

![image](https://github.com/kitajs/html/assets/47537704/3eed777c-1874-41c4-bc8b-acaf10c5a705)

**Comment by mvolkmann** [comment]
I don't know how to change the TS LSP setting in VS Code.
If I do that, will it affect other projects that I edit with VS Code?

**Comment by arthurfiorette** [comment]
the above print shows you how to do that. 

No it won't affect other projects as it is a per workspace configuration.
