### ISSUE TITLE
Feature Request: Support arbitrary attribute mutations, possibly at compile-time

### ISSUE THREAD

**Issue by mickmister** [kitajs/html#133]
I have a use case where I want to automatically spread certain attributes, like so:

```ts
const onClick: Htmx.Attributes = {
    'hx-get': '/api',
};

return <div {...onClick}/>;
```

I would love to be able to instead write this as:

```ts
return <div htmx={onClick}/>
```

and then somehow have a parser translate the `htmx` attribute into spreading the props after the fact.

Right now the [types are extendable](https://github.com/kitajs/html?tab=readme-ov-file#extending-types), but is it possible to add a piece of functionality to an attribute? Pseudocode for what I'm looking for

```ts
registerAttributeBehavior(props => {
    if (!'htmx' in props) {
        return props;
    }

    const htmxProp = props.htmx;
    delete props['htmx'];
    props = {...props, ...htmxProps};
    return props;
});
```

but hopefully this sort of translation can be done at compile time rather than runtime.

Related to https://github.com/kitajs/html/issues/132, as I want to be intentional with naming htmx attributes in my components, rather than use the spread operator.

**Comment by mickmister** [comment]
Wondering your opinion on implementing this in my application this way:

```ts
import Html from '@kitajs/html';

const originalCreateElement = Html.createElement;

Html.createElement = (type, props, ...children) => {
  if (props && props.htmx) {
    Object.assign(props, props.htmx);
    delete props.htmx;
  }

  return originalCreateElement(type, props, ...children);
};
```

**Comment by arthurfiorette** [comment]
It's better off if you change the `attributesToString` signature directly:

```js
const oldAttributesToString = Html.attributesToString;

Html.attributesToString = (attrs, safe) => {
  /// mutate your attrs obj
  return oldAttributesToString(attrs, safe);
}
```
