### ISSUE TITLE
[question] How do I ignore XSS errors on custom JSX components?

### ISSUE THREAD

**Issue by coindegen** [kitajs/html#149]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

`    "@kitajs/ts-html-plugin": "^1.3.4",`

### Description

Hi there, 

first off, love the project. Has been absolutely flawless so far.

I read the following in your docs (https://kitajs.github.io/ts-html-plugin/#special-cases) :

> Ternary and binary operations are evaluated in both sides separately and will throw errors if any of the sides is not safe, even their condition never gets hit at runtime.

I'm finding the XSS plugin exceedingly aggressive, finding errors where there shouldn't be. I'm hoping you can suggest some workarounds. Consider the following code:

```js
<div class="body">
              {collection.website && (
                <Badge externalUrl={collection.website} symbol="website" />
              )}
              {collection.twitter && (
                <Badge externalUrl={collection.twitter} symbol="x" />
              )}
              {collection.discord && (
                <Badge externalUrl={collection.discord} symbol="discord" />
              )}
</div>
```

Each of these gets flagged as xss-prone content as in the screenshot (whether I use short-circuiting above or switch to `? : ` syntax makes no difference.) This doesn't feel like the intention behind the plugin at all. 

I tried escaping the content like this:

```js
              {collection.website && (
                <Badge
                  externalUrl={Html.escapeHtml(collection.website)}
                  symbol="website"
                />
              )}
```

But it's still flagged as xss prone. 

I don't want to pass the `safe` attribute to the enclosing `<div>`, because `<Badge />` is a custom component comprising more JSX. 

a) Is there a way to mark a component `as "safe"`, like a string primitive?
b) Wouldn't it be more sensible to skip XSS warnings for custom JSX components? Maybe I'm missing something but I only care about that warning on standard HTML tags like `<div>`, `<span>`, `<p>`, etc...

Thanks very much.

<img width="652" alt="image" src="https://github.com/kitajs/html/assets/87461192/7fc5a121-f333-4d6d-ba82-c726889dd1f8">

### Steps to Reproduce

use above code snippet

**Comment by arthurfiorette** [comment]
https://github.com/kitajs/html/tree/master/packages/ts-html-plugin#handling-warnings

**Comment by arthurfiorette** [comment]
But I'm pretty sure this is related to https://github.com/kitajs/html/issues/146

**Comment by JacopoPatroclo** [comment]
@arthurfiorette I can take a look into this

**Comment by arthurfiorette** [comment]
Sure, go for it :)
