### ISSUE TITLE
Cannot find module '@kitajs/html/jsx-runtime' or its corresponding type declarations.

### ISSUE THREAD

**Issue by FedericoBiccheddu** [kitajs/html#150]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

```json
{
	"dependencies": {
		"@kitajs/html": "3.1.2",
		"@kitajs/ts-html-plugin": "1.3.4",
	},
	"devDependencies": {
		"typescript": "5.4.2",
	}
}
```

### Description

`jsx-runtime` is not installed/present in the `html` package.

![image](https://github.com/kitajs/html/assets/433819/62abf9c9-ae2c-4f14-a0f9-b2118be4417c)

### Steps to Reproduce

- Install dependencies.
- Update `tsconfig.json`:
  ```json
  {
    "extends": [
      "@tsconfig/strictest/tsconfig",
      "@tsconfig/node-lts/tsconfig",
    ],
    "compilerOptions": {
      "jsx": "react-jsx",
      "jsxImportSource": "@kitajs/html",
      "plugins": [
        {
          "name": "@kitajs/ts-html-plugin"
        }
      ]
    }
  }
  ```
- Add code to test like in `README`:
  ```tsx
  console.log(<div safe>{String.name}</div>);`
  ```
- Hovering:
  `Cannot find module '@kitajs/html/jsx-runtime' or its corresponding type declarations.ts(2307)`
- Compiling:
  `Error: Cannot find module '@kitajs/html/jsx-runtime'`

**Comment by anravell** [comment]
same problem

p.s. make new release please, I need alpine support, I see it's already done

**Comment by joncys** [comment]
I have the same problem. Very basic setup with express and @kitajs/html. Using `pnpm`, no idea if that's relevant.

The [alternative configuration method](https://github.com/kitajs/html/tree/master/packages/html#alternative-way-to-configure-your-tsconfig) seems to work fine.

```
import express from "express"
import Html from '@kitajs/html'

const html = (
  <div data-internet="wow">Hello</div>
)

const app = express()
app.get('/', (req, res) => {
  res.send(html)
})

app.listen(8080)
```

**Comment by arthurfiorette** [comment]
The main branch contains unreleased changes.

[Please browse the readme for the last released version: v3.1.2](https://github.com/kitajs/html/tree/v3.1.2)

**Comment by anravell** [comment]
@joncys is there some blocker to release this changes? may be I can help and do some PR's

now I'm forced to build it myself with pnpm --prod deploy to my project node_modules and it make everything very complex

i wanted to temporary just copy code to ./src/lib and setup it from here, but tsconfig jsxImportSource requires it to be a package in node_modules and cant work with relative path to source code, so everything became very problematic: ci/cd, explaing to teammates how to set it up

can I help somehow so you release it

**Comment by arthurfiorette** [comment]
> [Please browse the readme for the last released version: v3.1.2](https://github.com/kitajs/html/tree/v3.1.2)

**Comment by sarmong** [comment]
I did setup like mention in 3.1.2 readme and I get `cannot be used as a JSX component.` error.

This is the only thing I have in `tsconfig.json`

```jsonc
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "Html.createElement",
    "jsxFragmentFactory": "Html.Fragment",
    "plugins": [{ "name": "@kitajs/ts-html-plugin" }]
    }
}
```

And this is the `index.tsx` file

```
import "@kitajs/html/register";

function UserCard({ name }) {
  return (
    <div class="card">
      <h1 safe>{name}</h1>
    </div>
  );
}

export const Component = () => <UserCard name="John Doe" />;
```

Did I misunderstand anything?

**Comment by anravell** [comment]
> > [Please browse the readme for the last released version: v3.1.2](https://github.com/kitajs/html/tree/v3.1.2)

I did, but it says nothing about how to build main branch with unreleased changes to have alpine support in my project.

**Comment by arthurfiorette** [comment]
Copy this file into your definitions:

https://github.com/kitajs/html/blob/master/packages/html/alpine.d.ts

**Comment by arthurfiorette** [comment]
Hey @joncys @FedericoBiccheddu @anravell I just released `next` dist-tag. Would you guys mind trying it out?

`npm i @kitajs/html@next`

**Comment by FedericoBiccheddu** [comment]
Now it works, thank you Arthur!

**Comment by anravell** [comment]
@arthurfiorette thank you!

**Comment by 7f8ddd** [comment]
> Hey @joncys @FedericoBiccheddu @anravell I just released `next` dist-tag. Would you guys mind trying it out?
> 
> `npm i @kitajs/html@next`

I'm using Bun and it's still saying `error: Cannot find module "@kitajs/html/jsx-dev-runtime"`, 4.0.0@next.

**Comment by arthurfiorette** [comment]
Hey @7f8ddd, can you show your tsconfig?

**Comment by 7f8ddd** [comment]
> Hey @7f8ddd, can you show your tsconfig?
```
    "jsx": "react-jsx",
    "jsxImportSource": "@kitajs/html"
```

I think a Bun issue needs to be made, it's a Bun specific 
![image](https://github.com/kitajs/html/assets/141754874/cd9ad151-d088-4e94-b997-cce5fb21a3f3)
problem. 

I worked around it by just copying the jsx-dev-runtime file and changing the export from jsx to jsxDEV.

**Comment by JacopoPatroclo** [comment]
@arthurfiorette I feel that we should export both jsx and jsxDEV functions from the jsx-runtime file and also create a jsx-dev-runtime file. They should have the same signature, this should be an easy thing to do.

@7f8ddd you should open an issue to Bun about this. Bun should handle the difference between dev and prod when it bundles. For this library, the difference is zero but for something like React you should not use the dev mode in a prod build.

**Comment by arthurfiorette** [comment]
> I feel that we should export both jsx and jsxDEV functions from the jsx-runtime file and also create a jsx-dev-runtime file. They should have the same signature, this should be an easy thing to do.

Sure, this is probably the correct way to solve this.

However, I made some tests a week ago, [and this scared me a little bit](https://twitter.com/jarredsumner/status/1767311048225530011). Bun was rendering objects in production mode, even for KitaJS. Just like as if bun in prod mode was **react-only** compatible.

More tests using bun should be made, and probably also setup a CI for It.

**Comment by arthurfiorette** [comment]
Let's talk about it at #159.
