### ISSUE TITLE
No "alpine" exported on npm

### ISSUE THREAD

**Issue by xantiagoma** [kitajs/html#153]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

- 3.1.2
- all

### Description

On the published package https://www.npmjs.com/package/@kitajs/html/v/3.1.2?activeTab=code 
![CleanShot 2024-03-19 at 22 04 40@2x](https://github.com/kitajs/html/assets/1217807/4c34bf10-7fa5-4c07-ab45-27f8c0cdd602)
There's no exported [alpine.d.ts](https://github.com/kitajs/html/blob/master/packages/html/alpine.d.ts) and [alpine.js](https://github.com/kitajs/html/blob/master/packages/html/alpine.js) files that appears in the github repo.

### Steps to Reproduce

try to add `"types": ["@kitajs/html/alpine.d.ts"],` to `tsconfig.json` and linter throws.

**Comment by arthurfiorette** [comment]
Its correct, Alpine wasn't released for v3. Please switch to our `4.0.0-next` release.
