### ISSUE TITLE
Add `onchange` and `oninput` events for the `select` tag

### ISSUE THREAD

**Issue by gabor-s** [kitajs/html#177]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

3.1.2

### Description

There's no `onchange` and `oninput` event in the typings of `HmtlSelectTag`.

### Steps to Reproduce

https://github.com/kitajs/html/blob/9ca8cdfa00a62a45bfbb8b362931d3a1afd87062/jsx.d.ts#L448

**Comment by gabor-s** [comment]
Maybe other event attributes are missing too.

**Comment by arthurfiorette** [comment]
can you open a pr?

**Comment by gabor-s** [comment]
Sure. Do you know what event attributes are available on the HTML select tag?

**Comment by arthurfiorette** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by gabor-s** [comment]
I know this documentation, but it only mentions that "Events fired by <select>: change, input", but I think `onfocus` also meaningful for select tags.

**Comment by gabor-s** [comment]
Why is that every JSX library creates its own typings for `IntrinsicElements`? Isn't it the same for everyone?

**Comment by arthurfiorette** [comment]
Anyone who wants to help with this issue, feel free to create a PR

**Comment by gabor-s** [comment]
Sorry, but I don't have the time right now. 
I checked some other libraries. Preact uses its own types, but Solid for example uses types from [dom-expression](https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts) which also based on other libraries.

**Comment by JacopoPatroclo** [comment]
@arthurfiorette I can take this one. I'm not sure about the scope of this issue.
I think I should fix the missing types on the select HtmlSelectTag.
Then we should discuss how to improve this part of @kitajs/html deciding if we should use some open source typings for JSX or if we still use our definitions.
