### ISSUE TITLE
Improve `compile` declaration to avoid having to manually add `<typeof function>` as a generic parameters.

### ISSUE THREAD

**Issue by ethanniser** [kitajs/html#18]
love the new compile api, super cool how thats able to be done with `Proxy`
its great to just be able to pass in a *clean* component, and get out a new compiled one that type wise is identical

however I ran into some [strange type issues](https://gist.github.com/ethanniser/c1451e34f87d000f1dc4862053390118) (errors in comment of gist)

This might be solved by explicitly passing a generic, but the dx is so much better when that isnt necessary

After messing around a bit I refactored the type for `compile` and ended up with this

```ts
type StringPropsOnly<P> = {
  [K in keyof P]: string;
};

declare function myCompiled<P extends StringPropsOnly<P>>(
  this: void,
  component: (props: P) => JSX.Element,
  strict?: boolean,
  separator?: string
): (props: P) => JSX.Element;
```

which [resolved all of the issues I had](https://gist.github.com/ethanniser/bcf3f2771cac90310561e7fdc881828e)

---

The existing type still supports passing a tuple or record of strings, which I am assuming is a remnant from the old API.

Curious to your thoughts on this, but I think we should drop support for that, and just rely on inference from the function

---

thanks!

**Comment by arthurfiorette** [comment]
Hey @ethanniser. 

You can solve by using `typeof fn` as generics, like `html.compile<typeof Component>(Component)`.

Yes, I kept the string[] props because it was from the older API, however we bumped to v2, which is by itself a breaking change.

Happy to merge a PR with your proposed new type.
