### ISSUE TITLE
{false && <div>Render</div>} pattern is broken.

### ISSUE THREAD

**Issue by maltium** [kitajs/html#196]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

Issue noticed on 4.1.0, on 3.0.10 it worked fine.

### Description

This could be an intentional change, but as the title says, `{false && <div>Render</div>}` renders the text *false* in the DOM. My expectation would be that nothing is rendered.

### Steps to Reproduce

`{false && <div>Render</div>}` 

### Expected Behavior

Nothing is rendered to the DOM

**Comment by arthurfiorette** [comment]
#190
