### ISSUE TITLE
Cannot find module '@kitajs/html/jsx-runtime' or its corresponding type declarations with NodeJS and module package

### ISSUE THREAD

**Issue by mattdean-digicatapult** [kitajs/html#206]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

kitajs/html: 4.1.0
typescript: 5.4.5
node: 22.0.0

### Description

Cannot build a package with `"type": "module"` using `tsc` for NodeJS. Doing so seems to always result in the error `Cannot find module '@kitajs/html/jsx-runtime' or its corresponding type declarations`. I believe this is because the output is doing a deep `import` on a `jsx-runtime` without a file extension.

I do not believe this is a duplicate of https://github.com/kitajs/html/issues/150 even though it looks very similar. In that case everyone commenting was using Bun as the runtime in this instance I'm using Node. Apologies if I'm doing something silly.

### Steps to Reproduce

I've produced a repoduction at https://github.com/mattdean-digicatapult/kitajs-html-example. In short to reproduce checkout that repo and just do:

```
npm i
npm run build
```

build is just running `tsc` if you'd prefer

### Expected Behavior

The build to succeed.

**Comment by Markyiptw** [comment]
I got the same issue. `@kitajs/html` only works with CommonJS but not ES module in NodeJS.

**Comment by arthurfiorette** [comment]
Please use the alternative way to configure jsx until the next release

https://github.com/kitajs/html/tree/master/packages/html#alternative-way-to-configure-your-tsconfig

**Comment by arthurfiorette** [comment]
Just released `v4.2.0` which should fix this problem.
