### ISSUE TITLE
`CleanProps` is not exported

### ISSUE THREAD

**Issue by keuller** [kitajs/html#22]
## What expected?

```jsx
import { CleanProps } from "@kitajs/html"

function Clean(props: CleanProps<{ repeated: string }>) {
  return <div>{props.repeated}</div>
}
```

## Issue

 `CleanProps` type is not available.

**Comment by arthurfiorette** [comment]
Hey! That was a typo... You can use directly `{ repeated: string }` or `PropsWithChildren<{ repeated: string }>` if you need children.
