### ISSUE TITLE
Support the `popover` attribute

### ISSUE THREAD

**Issue by garrappachc** [kitajs/html#228]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

4.1.0

### Description

When I want to use the [popover attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover), e.g.:
```tsx
<div popover id="my-popover">Greetings, one and all!</div>
```
I get the following error:
```
error TS2322: Type '{ children: Element[]; popover: true; class: string; }' is not assignable to type 'HtmlTag'.
  Property 'popover' does not exist on type 'HtmlTag'.
```

### Steps to Reproduce

Use the `popover` attribute in a HTML tag.

### Expected Behavior

The `popover` attribute is typed as `'auto' | 'manual'`.

**Comment by arthurfiorette** [comment]
Hey @garrappachc, nice feature request, are you up to PR it?

**Comment by garrappachc** [comment]
> Hey @garrappachc, nice feature request, are you up to PR it?

Sure! I'll tackle this soon
