### ISSUE TITLE
Htmx + safe attribute doesn't work

### ISSUE THREAD

**Issue by Fecony** [kitajs/html#26]
Have simple example of Elysia/html plugin, kita and htmx

> Elysia endpoint

```ts 
app.post('/clicked', ({ html }) => html(<script>alert("hacked!")</script>))
```

> Component with htmx tags

```ts
const Component = () => (
	<button
		hx-post="/devtools/clicked"
		hx-trigger="click"
		hx-swap="innerHTML"
		safe
	>
		Click Me!
	</button>
)
```

results injecting and running js code...
maaaaaybe I need to sanitize it on server then?

<img width="452" alt="Screenshot 2023-09-17 at 00 49 06" src="https://github.com/kitajs/html/assets/36774784/39de5ae6-42fe-4b7d-a9a3-c5edf0fa2860">

**Comment by Fecony** [comment]
Sanitizing on server works as expected. I just wanted to make sure it is how htmx works there or if it can be fixed

![image](https://github.com/kitajs/html/assets/36774784/30dc377d-dfcc-4bd8-9934-1d1a09550166)

**Comment by arthurfiorette** [comment]
This is intended behavior. the safe attribute only has effects when the inner createElement call is made. No extra JS code is sent to the client, so there's no way to do that. You should use `safe` attribute where you would interpolate with user generated content, not as a html response sent from a server.

**Comment by Fecony** [comment]
Thanks for the clarification ❤️
