### ISSUE TITLE
Event of HtmlTag

### ISSUE THREAD

**Issue by tvinhkhoa** [kitajs/html#332]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

Nodejs: v20.18.0
Typescript: 5.6.3
react: 

### Description

export function Home() {
  const Click= () => {
    console.log(1)
  }

  return (
    <html>
      <body>
        <div>
          <h1>Hello World</h1>
          <button onClick={Click}>Click here</button>
        </div>
      </body>
    </html>
  )
}

When runtime it had rendering html to

<html>
  <head></head>
  <body data-new-gr-c-s-check-loaded="14.1208.0" data-gr-ext-installed="">
    <div>
      <h1>Hello World</h1>
      <button onclick="() => {
        console.log(1);
    }">Click here</button>
    </div>

but javascript of html is 
<button onclick="(() => {
        console.log(1);
    })()">Click here</button>

worked,
please check it

Nodejs: v20.18.0
Typescript: 5.6.3

### Steps to Reproduce

import type { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'
import { Home } from 'App/Views/Home'

export default class HomeController {
  async show({ ctx }: HttpContextContract) {
    return <Home />;
  }
}

### Expected Behavior

Work on event html tag

**Comment by arthurfiorette** [comment]
I couldn't understand your issue.

**Comment by arthurfiorette** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#event_handler_attributes
