### ISSUE TITLE
esbuild fails to use proposed `html` namespace

### ISSUE THREAD

**Issue by AjaniBilby** [kitajs/html#4]
When using the [proposed `tsconfig.json`](https://www.npmjs.com/package/@kitajs/html#getting-started) esbuild compiles in a way that attempts to use `React.createElement` to generate elements instead of the `html.createElement` namespace. This then results in an error because `React` is not defined anywhere.

I'm not sure of the exact issue, but changing the config to this fixes the issue:
```json
{
	"compilerOptions": {
		"jsx": "react",
		"jsxFactory": "elements.createElement",
		"jsxFragmentFactory": "elements.Fragment",
	}
}
```

With just [this commit](https://github.com/AjaniBilby/predictable/commit/2b03f94af61e5b122e47c49a66dd772833a2bba5) I got my server from runtime erroring attempting to use `React`, to actually using the library properly.  
*This issue only occurs when a tsx file is compiled using esbuild instead of tsc*
IDK if you want to just update the docs to mimic my config, or diagnose the issue root issue, but it's up ot you

**Comment by arthurfiorette** [comment]
Hey @AjaniBilby, If you use the following, would it work?

```jsonc
{
	"compilerOptions": {
		"jsx": "react",
		"jsxFactory": "html.createElement",
		"jsxFragmentFactory": "html.Fragment",
	}
}
```

And import with:

```ts
import html from '@kitajs/html'
// or
import * as html from '@kitajs/html';
```

?

**Comment by AjaniBilby** [comment]
Confirmed this does work [#54d932f](https://github.com/AjaniBilby/predictable/commit/54d932fa2afae951944a56d2e471d7152660469f)
