### ISSUE TITLE
Dialog tag definition is missing in JSX.IntrinsicElements

### ISSUE THREAD

**Issue by OrlandoCo** [kitajs/html#58]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

latest

### Description

`<dialog/>` Tag is missing in jsx definition causing type errors.

ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

Workaround

```ts
declare namespace JSX {
  interface IntrinsicElements {
    dialog: HtmlTag;
  }
}
```

### Steps to Reproduce

Set a `<dialog/>` tag and linter will get angry.

### Expected Behavior

no type errors

**Comment by arthurfiorette** [comment]
v3.0.6
