### ISSUE TITLE
`CSSProperties` type too permissive

### ISSUE THREAD

**Issue by nsaunders** [kitajs/html#60]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

v3.0.5

### Description

The [`CSSProperties` type](https://github.com/kitajs/html/blob/7416c3b74bbdc3c239dd874b62fe633f7fa8f467/jsx.d.ts#L29) currently accepts string, number, or boolean length values. (For reference: [csstype's `Properties` interface](https://github.com/frenic/csstype/blob/master/index.d.ts#L8898))

However, it doesn't appear that the [`styleToString` function](https://github.com/kitajs/html/blob/7416c3b74bbdc3c239dd874b62fe633f7fa8f467/index.js#L128) actually handles numeric or boolean length values.

IMHO the easiest fix is probably just to change the `TLength` arg to simply `string`.

### Steps to Reproduce

Try something like `style={{ width: 100 }}` and review the resulting HTML output.

### Expected Behavior

The expected behavior for a numeric length value (judging by React's functionality, anyway) is for the resulting style attribute to be `style="width: 100px"`. Since the `px` units aren't added implicitly here, a numeric length value shouldn't be allowed.

**Comment by arthurfiorette** [comment]
v3.0.6

**Comment by nsaunders** [comment]
Wow, thanks for the super quick response @arthurfiorette!

If I'm understanding correctly, it looks like you're appending `px` to any number value. Unfortunately, that doesn't account for unitless CSS values like for `line-height`, `flex-grow`, `z-index`, etc. This is a really easy detail to miss--I'm only familiar with it from recent work I did on my CSS Hooks project which has to mimic React's algorithm for stringifying values.

One option would be to use [@emotion/unitless](https://www.npmjs.com/package/@emotion/unitless) to determine whether `px` should be appended based on the property name.

Another option would be to copy [Preact's algorithm](https://github.com/preactjs/preact/blob/4fea40d1124ba631f8a11c27f6e71e018136318e/src/diff/props.js#L36-L46).

**Comment by arthurfiorette** [comment]
Oh, I totally missed this one... With that complexity, I think we should just go back to the previous behavior of blindly using the user input without never adding the `px` and making the user manually apply the `px` when needed. You're up to a PR?

**Comment by nsaunders** [comment]
Hi @arthurfiorette, I went ahead and submitted a PR: #61
