### ISSUE TITLE
console.log(<div>{'<' + '/div>'}</div>); not erroring on codespaces

### ISSUE THREAD

**Issue by andreirtaylor** [kitajs/html#85]
### Prerequisites

- [X] I have searched existing issues to ensure the bug has not already been reported

- [X] I have written a descriptive issue title

### Versions

Only tested on latest versions as of Dec 19, 2023

### Description

It doesn't seem like the xss vsCode extension is working. Additionally I don't think the xss-scan command is working as it does not seem to catch very obvious xss vulnerabilities (see below)

![image](https://github.com/kitajs/html/assets/6440936/c65f0b2f-5a5b-4ea4-9bf5-aec928092217)
 

### Steps to Reproduce

1. Open https://github.com/kitajs/minimal-example?tab=readme-ov-file in a codespace
2. paste in `console.log(<div>{'<' + '/div>'}</div>);`

### Expected Behavior

The above should error based on what I have read in the [readme here](https://github.com/kitajs/html?tab=readme-ov-file#be-sure-your-setup-is-working-correclty) but it does not seem to have any effect.

**Comment by arthurfiorette** [comment]
Latest `ts-html-plugin` is smart enough to detect `'a' + 'b'` results into `'ab'`, which is a string literal and should not be typed. Just updated the readme to fix this problem.
