### ISSUE TITLE
Compilation issue with TypeScript in versions >= @kitajs/html@3.0.4

### ISSUE THREAD

**Issue by haricane8133** [kitajs/html#86]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

@kitajs/html@3.0.4 and above

### Description

I am experimenting @kitajs/html and @kitajs/ts-html-plugin in a NodeJS Express application serving HTMX, for using JSX in development.

The app is throwing the following TypeScript compilation error when I have installed version 3.0.4 or above

```
node_modules/@kitajs/html/suspense.d.ts:23:17 - error TS2304: Cannot find name 'WeakRef'.

23         stream: WeakRef<HtmlStream>;
                   ~~~~~~~

Found 1 error in node_modules/@kitajs/html/suspense.d.ts:23
```

I am not sure about the fix, but this seems to have started the issue - https://github.com/kitajs/html/compare/v3.0.3...v3.0.4#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R2

### Steps to Reproduce

**Initial Steps**
1. Clone the repo - https://github.com/haricane8133/htmx-jsx-express-stack
2. `npm ci`

**Build succeeds** (@kitajs/html@3.0.3 used)
-  `npm run build`

**Build fails** (@kitajs/html@3.0.4 used)
- `npm install --save-dev --save-exact @kitajs/html@3.0.4`
- `npm run build`

**Comment by arthurfiorette** [comment]
You are using a `es5` target in your tsconfig and only `es6` lib, please increase it to something maintained to this day, like `es2019`.

**Comment by haricane8133** [comment]
@arthurfiorette, thanks for the response. However, the same error is still returned to me even after updating both the lib and target to `es2019`.

Please reopen this issue. I am unable to do so from my end.

**Comment by arthurfiorette** [comment]
Do you have `@types/node` installed?

**Comment by arthurfiorette** [comment]
![image](https://github.com/kitajs/html/assets/47537704/2bc12851-6ec8-4089-8a6b-0f10e80c7891)

I forked your reproduction repository and could get it to work normally. The issue is not in the `@kitajs/html` side. 

Also, no other people are also having the same problem. Feel free to reopen.

**Comment by haricane8133** [comment]
Hi @arthurfiorette. I have used the working version of @kitasjs/html@3.0.3 in my repo, and therefore it would work.

Please have a look at the "Steps to Reproduce" section of my initial comment in this issue.
You need to install version @kitasjs/html@3.0.4 or above to reproduce the issue.

Please reopen the issue. I am not having the button enabled to reopen.

Thanks.

**Comment by arthurfiorette** [comment]
Sorry, I overlooked your previous repository.

> WeakRef requires ES2021 typings (node 14+) to be installed. 

https://github.com/kitajs/html/blob/cbb29c9a2e99bef277135c31e2847c3c461a2308/suspense.d.ts#L52-L57

You `tsconfig` is using a **target released 3100 days ago**. Why are you transpiling to es5? and only adding es6 lib. Please update it to at least 2021.

```diff
-    "target": "es5",
-    "module": "commonjs",
-    "lib": ["es6"],
+    "target": "ES2021",
+    "module": "commonjs",
```

**Comment by arthurfiorette** [comment]
Additionally, you can just update your lib configuration.

```diff
- "lib": ["es6"],
+ "lib": ["es6", "ES2021.WeakRef"],
```
