### ISSUE TITLE
Vitejs - ReferenceError: Html is not defined (Import Html on every file?)

### ISSUE THREAD

**Issue by ClementLaval** [kitajs/html#89]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

    "@kitajs/html": "^3.0.10",
    "@kitajs/ts-html-plugin": "^1.3.3",

### Description

Hi, first thanks to produce this lib, it's very usefull for the stack I want to use ❤️

I'm actually using it with Vite js, all works fine on development.
I registred globally kita on entry-server.tsx, which is the main entry.
![image](https://github.com/kitajs/html/assets/82887830/571946f3-fe27-4232-b215-d0d81e622bb0)

But when I build my project and start it, I got this error.
![image](https://github.com/kitajs/html/assets/82887830/339dff5e-429d-443d-acaa-f301ad8db1c0)

This is a part of the code I got /dist folder

![image](https://github.com/kitajs/html/assets/82887830/72693568-2287-4946-964c-55ecc243ff41)

The only way found to fix the problem is to: `import { Html } from '@kitajs/html';` on every .tsx files. 
Which not is not convenient.

There is a way to import this Html globally?

### Steps to Reproduce

```
//tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "skipLibCheck": true,
    /* Bundler mode */
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    /* Kita */
    "jsx": "react",
    "jsxFactory": "Html.createElement",
    "jsxFragmentFactory": "Html.Fragment",
    "plugins": [
      {
        "name": "@kitajs/ts-html-plugin"
      }
    ]
  },
  "include": [
    "src"
  ]
}
```

**Comment by arthurfiorette** [comment]
Hey @ClementLaval, can you provide a reproducible example?

**Comment by ClementLaval** [comment]
Yep,
[https://github.com/ClementLaval/kitajs-vite](https://github.com/ClementLaval/kitajs-vite)
