### ISSUE TITLE
JSX type definitions in conlfict with react

### ISSUE THREAD

**Issue by LukasBombach** [kitajs/html#90]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

Tested with 3.0.10

### Description

I have installed `@kitajs/html` as an inderect dependency of `@elysiajs/html`. Now I get Typescript errors in my project in random JSX properties, for example

```tsx
<meta charSet="UTF-8" />
//    ^^^^^^^ 
//           Property 'charSet' does not exist on type 'HtmlMetaTag'. Did you mean 'charset'?ts(2322)
```

React's types defined this attribute to be written in camel case, ie. `charSet` while `@kitajs/html` overrides this with the all lowercase `charset`. Other examples are event handlers like `onClick` or `onKeyPress`

To me this is unexpected und unpractical because all my other projects use React's definitions as lingua franca

### Steps to Reproduce

Setup a project with Next js and use this component

```tsx
const Button = () => <button onClick={() => {}}>click</click>
```

You will see no type Errors. Install `@kitajs/html` and you will get type errors ot `onClick`

### Expected Behavior

KitaJs matches, re-exports or expects React's TS Definitions as a peer dependency instead of providing divergent types

**Comment by arthurfiorette** [comment]
> React's types defined this attribute to be written in camel case, ie. charSet while @kitajs/html overrides this with the all lowercase charset. Other examples are event handlers like onClick or onKeyPress

This is not react, this project does not have anything in common with React without by both using JSX. `charSet` html property is lowercase, so `kitajs/html` repescts this value. `Kitajs/html` tags renders to string, so `onClick` and all others functions CANNOT be used here. Kitajs/Html is a template engine.

**Comment by arthurfiorette** [comment]
Typescript spec uses the `JSX` namespace to correctly define its types. React and Kitajs/Html cannot be defined in the global namespace, you can import kitahtml in each file and use a _jsx pragma comment_ to use it.

**Comment by arthurfiorette** [comment]
Besides that, are you having problems when generating html strings with kitajs/html?

**Comment by LukasBombach** [comment]
I understand that this project has nothing in common, so to speak, with react, other that both work with JSX. What I am intending here is that even though this project is not related to react, react has established defininitions (a lingua franca) for camel case JSX attributes. Now when someone uses this project with TypeScript, they will have use all-lowercase attributes, while in all their other projects, they will use camel-case attributes. To me, switching between styles, is usually a cognitive pain.

In my case, I am neither using react _nor_ am I using your project directly. I am acutally using [ElysiaJS](https://elysiajs.com/) which, for [it's html plugin](https://elysiajs.com/plugins/html.html) uses your project internally. My issue here is, once I install the html plugin, your projects JSX TypeScript definitions, will override the JSX TypeScript definitions I had before and most of my .tsx files become errorneous, only because this is a dependency of a dependency that I use.

**Comment by LukasBombach** [comment]
So whether or not Kitajs renders `onClick` or not, it will break the types for it

**Comment by LukasBombach** [comment]
And I am pretty sure there are ["official" types](https://www.typescriptlang.org/docs/handbook/jsx.html) that can be installed somehere or somehow, personally, I believe it would make sense to let each project decide which version of that to use, because surely in a project there are always other dependencies relying on JSX and their types.

**Comment by arthurfiorette** [comment]
> And I am pretty sure there are ["official" types](https://www.typescriptlang.org/docs/handbook/jsx.html) that can be installed somehere or somehow

Typescript does not provides JSX type definitions, it uses the `JSX` namespace and expects it to be defined by something in each project, in your case is being double declared by `React` and `Kitajs/Html`.

**Comment by arthurfiorette** [comment]
> surely in a project there are always other dependencies relying on JSX and their types.

Nope, in fact this is rare enough they didn't think of adding support for multiple JSX definitions. Either you use one declared globally, or a imported one per file.

**Comment by arthurfiorette** [comment]
> So whether or not Kitajs renders onClick or not, it will break the types for it

It must complain about the `onClick` type, as it is not a property kitajs html can handle (functions in general).

**Comment by arthurfiorette** [comment]
Anyways, without a reproducible example, I cannot help you with your specific use case. Your setup is misconfigured and interpreting both React and Kitajs/Html globally, you should fix it. 

we cannot fix this problem in our side. Feel free to open another issue if you have other problems 😊

**Comment by dominictobias** [comment]
> ject internally. My issue here is, once I install the html plugin, your projects JSX TypeScript definitions, will override the JSX TypeScript definitions I had before and most of my .tsx files become errorneous, only because this is a dependency of a dependency that I use.

Did you find a solution? Spend all day on this. Tried a monorepo and seperate packages for UI and API, as soon as I import `App` from Elysia all types break in the React project - even if they are separate packages in a monorepo

**Comment by dominictobias** [comment]
Here is a repro @arthurfiorette - just comment and uncomment this line: https://github.com/dominictobias/kitajs-breaks-react-types/blob/main/ui/src/App.tsx#L6

**Comment by arthurfiorette** [comment]
This line below loads the `@api` into the type definitions.

https://github.com/dominictobias/kitajs-breaks-react-types/blob/4d388224c977ee7106698aadd6e55061320f5817/ui/src/App.tsx#L6

And here, inside your `@api`, loads kita JSX into type definitions.

https://github.com/dominictobias/kitajs-breaks-react-types/blob/4d388224c977ee7106698aadd6e55061320f5817/api/src/index.ts#L5

This is making both JSX type definitions available at runtime. You need to figure a way to not load both of them.

This is not a kitajs issue. Feel free to reopen if more help is needed.
