### ISSUE TITLE
hx-sync attribute type error

### ISSUE THREAD

**Issue by adicco** [kitajs/html#95]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

- "@kitajs/html": "^3.0.10"
- "typescript": "^5.0.0"

### Description

When setting `hx-sync` to `this:replace`, which is a valid value [according to htmx's docs](https://htmx.org/attributes/hx-sync/), I encounter the following TypeScript error:

![image](https://github.com/kitajs/html/assets/51270459/f77f517a-1403-48f4-a46f-b281db6d80eb)

Is it because of the way the `HxSync` union is defined?

### Steps to Reproduce

```html
<textarea hx-sync="this:replace"></textarea>
```

### Expected Behavior

No TypeScript error is raised when `hx-sync` is set to `this:replace`

**Comment by arthurfiorette** [comment]
Hey, you are up to a PR?

**Comment by arthurfiorette** [comment]
Fixed in v3.0.11
