### ISSUE TITLE
Support `.` in attribute names

### ISSUE THREAD

**Issue by dullkingsman** [kitajs/html#97]
## Problem

I am trying to use Alpine JS for a bit of client-side interactivity and it has directives that use syntax that are not supported. I was able to bypass some of them, but there is no way around some of them. For example,

``` html
<input @click="...">
```

could be updated to work as 

```html
<input x-on:click="...">
```

but something like: 

```html
<input x-on:keyup.enter="...">
```

is not possible to include because of the `.` and Alpine does not provide alternatives. 

## Suggestion

It would be great to provide support for this. Or maybe provide a way to escape illegal characters.

**Comment by arthurfiorette** [comment]
Hey @dullkingsman, I'm not sure how to support it, as `.`s inside attribute names are outside of the JSX syntax support...

**Comment by Farishadibrata** [comment]
`<button type="button" {...{["@click"]: "open = !open"}}>Click to open </button>`

[with deconstruct](https://github.com/facebook/jsx/issues/21#issuecomment-62256096) it does work, but the syntax just awful

**Comment by arthurfiorette** [comment]
A custom `attr` property could also be added, in which its usage would be the following:

```tsx
<div attrs={`x-on:click="..."`} />
```

renders to:

```html
<div x-on:click="..." />
```

Are you open to a PR?

**Comment by Farishadibrata** [comment]
I had issue with Typescript where it can't detect attrs attributes (i tried adding attrs to HtmlTag) you may want to review my code.
I made PR regarding this issue, apologize  if i made mistakes its my first time contributing OSS. Thank you !
